---
title: "Intrahost model"
author: "JT McCrone"
date: "4/18/2017"
output: html_document
---

```{r,echo=F}
require(knitr)
require(ggplot2)
require(plyr)
require(reshape2)
require(extrafont)
require(wesanderson)
require(grid)
require(tidyverse)
require(magrittr)

set.seed(42) # Set seed so randomization is reproducible
opts_chunk$set(fig.align="center",warning=FALSE,tidy=T,cache = T,echo=F)
theme_set(new = theme_classic()+ theme( # to make nice plots
axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),
axis.line.y = element_line(colour ='black',size=0.5,linetype='solid'),
text=element_text(family="Arial",size = 18))) 
# A couple options for color palletes
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
cbPalette<- wes_palette("Zissou")

source("../scripts/useful_functions.R")
require(cowplot)
```

```{r}

meta<-read.csv("../data/reference/all_meta.sequence_success.csv",colClasses = c('onset'='Date','collect'='Date'),stringsAsFactors = F)
intra<-read.csv("Intrahost_initially_present.csv",colClasses = c('onset'='Date'))



intra %>% mutate(collect.1 = meta$collect[match(SPECID.1,meta$SPECID)], collect.2 =meta$collect[match(SPECID.2,meta$SPECID)],DPS.1 = collect.1-onset,DPS.2 = collect.2-onset) ->intra
intra<-subset(intra,freq1<0.5) # Just to make sure


intra %>% group_by(ENROLLID) %>% 
  summarize(onset = unique(onset),
            within_host_time = unique(within_host_time),
            DPS.1 = unique(DPS.1),
            DPS.2 = unique(DPS.2)) -> intra_meta

intra_meta<-intra_meta[order(intra_meta$DPS.1,decreasing = T),]
intra_meta %>% mutate(DPS.2 = ifelse(DPS.1==DPS.2,yes = DPS.2+0.3,no = DPS.2)) ->intra_meta
intra_meta$sort_order<-1:nrow(intra_meta)
fig_2A<-ggplot(intra_meta,aes(x = DPS.1,xend=DPS.2,y = sort_order,yend=sort_order))+geom_segment(color = cbPalette[1])+ylab("")+xlab("Day post symptom onset")+ theme(axis.line.y=element_blank(),axis.ticks.y = element_blank(),axis.text.y = element_blank())+geom_point(aes(y=sort_order,x = DPS.1),color=cbPalette[1])+geom_point(aes(y = sort_order,x = DPS.2),color=cbPalette[1]) + scale_x_continuous(breaks = -2:6) 

fig_2A

save_plot("./Figures/Figure2A.pdf", fig_2A,
          base_aspect_ratio = 1.3)
embed_fonts("./Figures/Figure2A.pdf")
write.csv(intra_meta,"./Figures/data/Figure2A.csv")
```

```{r}
same_day<-subset(intra,within_host_time==0 & freq1<0.5)
Sup_4<-ggplot(same_day,aes(x=freq1,y=freq2))+geom_point()+
  xlab("Frequency in home isolate") + ylab("Frequency in clinic isolate") + 
  scale_x_continuous(limits = c(0,0.5))+scale_y_continuous(limits = c(0,0.5))
Sup_4

lm_fit<-lm(freq2~freq1,same_day)
summary(lm_fit)->sum_fit
sum_fit

write_to_summary("R2 samples same day:",sum_fit$r.squared)
save_plot("./Figures/Supplemental_Figure4.pdf", Sup_4,
          base_aspect_ratio = 1.3)
embed_fonts("./Figures/Supplemental_Figure4.pdf")


```



```{r}
stat_sum_df <- function(fun, geom="crossbar", ...) {
  stat_summary(fun.data = fun, geom = geom, width = 0.2, ...)
}

iqr_min <-function(x) quantile(x,probs = 0.25)
iqr_max <-function(x) quantile(x,probs = 0.75)

intra.plot<-ggplot(intra,aes(x=as.factor(within_host_time),y=freq2-freq1,fill=donor_class))+xlab("Time within host (days)")+ylab("Change in frequency")+
  scale_fill_manual(labels  =c( "Nonsynonymous","Synonymous"),
                    name="",values=cbPalette[c(1,4)])+
  geom_dotplot(stackdir = "center",binaxis = 'y',binwidth = 0.02,dotsize = 0.6,
               position=position_dodge(width = 0.95))+
  #stat_summary(fun.y = "median",fun.ymin =  "iqr_min",fun.ymax = "iqr_max",  geom = "crossbar",
  #             position = position_dodge(width = 1,preserve = 'single'),
  #             aes(color = donor_class,fill=NA))+
  #scale_color_manual(labels  ="",name="",values=cbPalette[c(1,4)])+
  theme(legend.position = 'none')

  
intra.plot
save_plot("./Figures/Figure2B.pdf", intra.plot,
          base_aspect_ratio = 1.3)

embed_fonts("./Figures/Figure2B.pdf")
write.csv(intra,"./Figures/data/Figure2B.csv")

intra %>% subset(within_host_time==1) %>% .$ENROLLID %>% unique() %>% length()->one_day_isnv
intra %>% subset(within_host_time>0) %>% .$ENROLLID %>% unique() %>% length()->at_least_day_isnv


write_to_summary("Samples exactly 1 day apart:",one_day_isnv)
write_to_summary("Samples at least 1 day apart:",at_least_day_isnv)
```

### Are the iSNV independent

```{r}
intra %>%  mutate(delta = abs(freq2-freq1))->intra

var_data<-data.frame(delta=intra$delta,freq2=intra$freq2,group = factor(intra$ENROLLID),time = factor(intra$within_host_time))

diffs = c()
group = c()
df = data.frame(diffs,group)
for(i in 1:(nrow(intra)-1)){
  for (j in (i+1):nrow(intra)){
    if(intra$within_host_time[i] == intra$within_host_time[j]){
      d=abs(intra$delta[i]-intra$delta[j])
      g = ifelse(test = intra$ENROLLID[i]==intra$ENROLLID[j],
                     yes = "Within_host",no = "Between_host")
      df<-rbind(df,data.frame(diffs=d,group=g))
    }
  }
}

ggplot(df,aes(x = diffs,y=..ncount..,fill=group))+
  geom_histogram(color="white",binwidth = 0.01,position = position_dodge()) +
  scale_fill_manual(labels  =c("Between hosts","Within host"),name="",values=cbPalette[c(1,4)])
  

ggplot(df,aes(y = diffs,x=group,fill=group))+
  geom_boxplot() +
  scale_fill_manual(labels  =c("Between hosts","Within host"),name="",values=cbPalette[c(1,4)])
wilcox.test(diffs~group,df,alternative='g')
```




If we pick 1/ person

```{r}
one_per<-read.csv("./one_per_person.csv")
ggplot(one_per,aes(x= Ne))+geom_histogram(color="white",binwidth = 1)
summary(one_per)
```
### Simulations

```{r}
sim.df<-read.csv("./simulated_fits.csv")

write_to_summary("Simulations mean 30:",mean(sim.df$X30))
write_to_summary("Simulations mean 50:",mean(sim.df$X50))
write_to_summary("Simulations mean 100:",mean(sim.df$X100))

sim.df.l<-data.frame(outcomes = c(sim.df$X30,sim.df$X50,sim.df$X100),Ne = rep(c(30,50,100),each = nrow(sim.df)))

fig_2C<-ggplot(sim.df.l,aes(y = outcomes,x = as.factor(Ne)))+geom_boxplot()+scale_y_continuous(limits = c(0,240),breaks=seq(0,240,20))+xlab("Expected Ne")+ ylab("Estimated Ne") #geom_abline(slope=1,intercept = 0,linetype=2)+
fig_2C
save_plot("./Figures/Figure2C.pdf", fig_2C,
          base_aspect_ratio = 1.3)
embed_fonts("./Figures/Figure2C.pdf")
write.csv(sim.df.l,"./Figures/data/Figure2C.csv")


```



###  Effect of removing data

```{r}
# copied from notebook 
#steps<-data.frame(Ne = c(32.0,37.0,42.0,50.0,52.0,54.0,56.0,59.0,60.0,61.0,67.0,70.0,76.0,77.0,86.0,109.0,135.0,140.0,154.0,155.0,150.0,151.0,154.0,165.0,175.0,183.0,190.0,197.0,188.0,195.0,201.0,191.0,181.0,202.0,207.0,241.0,226.0,215.0,253.0,239.0,222.0,273.0,453.0))
every_nth <- function(x, nth, empty = TRUE, inverse = FALSE) # Fromhttps://stackoverflow.com/questions/34533472/insert-blanks-into-a-vector-for-e-g-minor-tick-labels-in-r
  {
  if (!inverse) {
    if(empty) {
      x[1:nth == 1] <- ""
      x
      } else {
        x[1:nth != 1]
        }
    } else {
      if(empty) {
        x[1:nth != 1] <- ""
        x
        } else {
          x[1:nth == 1]
        }
    }
}

custom_breaks = seq(0,500,50)
#steps$removed<-0:(nrow(steps)-1)/(nrow(subset(intra,freq1<0.5))-nrow(same_day))
steps<-read.csv("./removed_data.csv")
fig_2D<-ggplot(steps,aes(x=removed,y = Ne))+geom_line()+
  xlab("Fraction iSNV removed") + ylab("Estimated Ne")+
  geom_point(data=steps[1,])+
  #geom_abline(slope=0,intercept = steps$Ne[1]*10,linetype=2)+
  scale_x_continuous(limits = c(0,0.9),breaks = seq(0,0.9,0.1))+
  scale_y_continuous(limits = c(0,500),breaks = custom_breaks,
                     labels= every_nth(custom_breaks,2,inverse = T))
fig_2D
save_plot("./Figures/Figure2D.pdf", fig_2D,
          base_aspect_ratio = 1.3)
#embed_fonts("./Figures/Figure2D.pdf")
write.csv(steps,"./Figures/data/Figure2D.csv")

steps %>% subset(Ne>320)  ->ten_fold
first_above<- subset(ten_fold,Ne==min(ten_fold$Ne))
write_to_summary("Fraction to increase by 10-fold:",first_above$removed)
```
# Gif example

```{r,eval=F}
diff_ex.df<-read.csv("./diffusion_example.csv")

pdf(file="./Figures/diffusion_examples.pdf", width=10, height=10)
for (i in unique(diff_ex.df$Days)){
df = subset(diff_ex.df,Days==i)
df$Probability[df$Frequency %in% c(0,1)]=df$Probability[df$Frequency %in% c(0,1)]*20
print(ggplot(df,aes(x=Frequency,y=Probability))+geom_line(color=cbPalette[1],size=3)+scale_y_continuous(limits=c(0,5),labels = c(rep("",6)))+ylab("")+theme(axis.ticks.y = element_blank(),axis.title.x = element_text(size=36),axis.text.x = element_text(size=28) ))
}
dev.off()

system("convert -delay 20 ./Figures/diffusion_examples.pdf ./Figures/diffusion_examples.gif")
```
