---
title: "Supplemental"
output: html_document
---

```{r,echo=F}
require(knitr)
require(ggplot2)
require(plyr)
require(reshape2)
require(extrafont)
require(wesanderson)
require(cowplot)
set.seed(42) # Set seed so randomization is reproducible
opts_chunk$set(fig.align="center",warning=FALSE,tidy=T,cache = T,echo=F)
theme_set(new = theme_classic()+ theme(
axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),
axis.line.y = element_line(colour ='black',size=0.5,linetype='solid'),
text=element_text(family="Arial Narrow",size = 18))) # to make nice plots
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
cbPalette<-wes_palette("Zissou")
source("../scripts/useful_functions.R")
```


```{r}
require(magrittr)
require(tidyverse)
cov.files<-c("../data/processed/HK_1/all.coverage.csv","../data/processed/HK_2/all.coverage.csv","../data/processed/HK_6/all.coverage.csv","../data/processed/HK_7/all.coverage.csv","../data/processed/HK_8/all.coverage.csv","../data/processed/cali09/all.coverage.csv","../data/processed/cali09_2/all.coverage.csv","../data/processed/victoria/all.coverage.csv","../data/processed/victoria_2/all.coverage.csv","../data/processed/perth/all.coverage.csv","../data/processed/perth_2/all.coverage.csv")
cov<-read_rbind(cov.files,c("HK_1","HK_2","HK_6","HK_7","HK_8","cali09","cali09_2","victoria","victoria_2","perth","perth_2"))
```

```{r,fig.width = 10}
cov_plot(cov,title = "Coverage") ->coverage.plot

require(cowplot)

# save_plot("./Figures/Supplemental_1.pdf", coverage.plot,base_width = 15.0,
#           base_aspect_ratio = 1.1)

coverage.plot
```


Here are the minor nonsynounous mutations in H3N2 and H1N1 samples named as amino acid position and variant in the HA numbering skeme.
```{r}
minor<-read.csv("./minor_nonsynom.cvs",stringsAsFactors = F,colClasses = c('onset'='Date','collect'='Date'))

minor %>% subset(pcr_result=="A/H3N2") %>%.$H3_name ->H3

minor %>% subset(pcr_result=="A/H1N1") %>%.$H1_name ->H1


```

H3N2 : `r H3`
H1N1 : `r H1`

These were pasted into nextflu and their frequencies downloaded. None of the H1N1 minor positions were found in next flu.

All the samples here we taken in december 2015.
```{r}



require(lubridate)
nextflu<-read.table("./minorH3_frequencies_nextflu.tsv",header = T)

require(tidyverse)
require(directlabels)

nextflu %>% gather(mutation,frequency,-x)->nextflu.l

nextflu.l %>% mutate(mutation=gsub("(.*)\\.(.*)","\\1:\\2",mutation))->nextflu.l

minor %>% filter(pcr_result=="A/H3N2") ->H3_minor

H3_minor %>% subset(H3_name %in% nextflu.l$mutation & pcr_result=="A/H3N2",
                 select = c(collect,SPECID,H3_name,freq.var)) ->collection_points

kable(collection_points)

nextflu.p<-ggplot(nextflu.l,aes(x=x,y=frequency,color=mutation))+
  geom_line()+scale_color_manual(values = 
                                   c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7"))+
  ylab("Global Frequency")+xlab("Year")+
  scale_x_continuous(breaks = seq(2005,2017,by=2))+geom_vline(xintercept =2015,linetype=2,alpha=0.5)
nextflu.p

nextflu.p
nextflu.p<-direct.label(nextflu.p,"angled.boxes")

#nextflu.p<-direct.label(nextflu.p,c("first.qp"))
nextflu.p<-direct.label(nextflu.p,c("last.qp"))
nextflu.p

# save_plot("./Figures/Supplemental_5.pdf", nextflu.p,
#           base_aspect_ratio = 1.3)
# embed_fonts("./Figures/Supplemental_5.pdf")

```

```{r}

require(lubridate)
nextflu<-read.table("./majorH3_frequencies_nextflu.tsv",header = T)

require(tidyverse)
require(directlabels)

nextflu %>% gather(mutation,frequency,-x)->nextflu.l

nextflu.l %>% mutate(mutation=gsub("(.*)\\.(.*)","\\1:\\2",mutation))->nextflu.l

nextflu.p<-ggplot(nextflu.l,aes(x=x,y=frequency,color=mutation))+
  geom_line()+
  ylab("Global Frequency")+xlab("Year")+
  scale_x_continuous(breaks = seq(2005,2017,by=2))+geom_vline(xintercept =2015,linetype=2,alpha=0.5)
nextflu.p

nextflu.p
#nextflu.p<-direct.label(nextflu.p,"angled.boxes")

nextflu.p<-direct.label(nextflu.p,c("first.qp"))
nextflu.p<-direct.label(nextflu.p,c("last.qp"))
nextflu.p
```