---
title: "ABC"
output:
  pdf_document: default
  html_document: default
---

```{r,echo=F}
require(knitr)
require(ggplot2)
require(tidyverse)
require(extrafont)
require(wesanderson)
require(magrittr)
require(HIVEr)
require(ggridges)
set.seed(42) # Set seed so randomization is reproducible
opts_chunk$set(fig.align="center",warning=FALSE,tidy=T,cache = T,echo=F)
theme_set(new = theme_classic()+ theme( # to make nice plots
axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),
axis.line.y = element_line(colour ='black',size=0.5,linetype='solid'),
text=element_text(family="Arial",size = 18))) 
# A couple options for color palletes
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
cbPalette<- wes_palette("Zissou")
require(cowplot)
#source("../scripts/useful_functions.R")

####### Write to summary results file ######
write_to_summary<-function(line_pattern,value){
  file = readLines("./results.table.tsv")
  line_pattern_regex = paste0("^",line_pattern)
  line = grep(line_pattern_regex,file)
  file[line] = paste0(line_pattern,"\t",value)
  writeLines(file,"./results.table.tsv")
}
```


```{r}
intra<-read_csv('../data/processed/secondary/Intrahost_initially_present.csv')
intra %>% subset(within_host_time==1 & freq1<0.5 & freq1>0) ->minor
minor %>% mutate(SPECID1_location = paste0(SPECID1,"_",chr,pos),
                 SPECID2_location = paste0(SPECID2,"_",chr,pos))->minor
qual<-read_csv("../data/processed/secondary/qual.snv.csv",
               col_types = list(
                 ENROLLID= col_character(),
                 SPECID = col_character(),
                 LAURING_ID = col_character(),
                 Id = col_character()
               ))
qual  %>% mutate(coverage = cov.tst.fw+cov.tst.bw,SPECID_location = paste0(SPECID,"_",chr,pos)) ->qual

minor %>% group_by(ENROLLID) %>% 
  group_by(mutation) %>%
  mutate(cov1 = qual$coverage[match(SPECID1_location,qual$SPECID_location)],
         cov2 = qual$coverage[match(SPECID2_location,qual$SPECID_location)])->minor
stopifnot(min(c(minor$cov1,minor$cov2),na.rm = T)>1000)

minor %>% mutate(sample1 = 1000,
                 sample2=1000)->minor

 plyr::adply(minor,1,function(x){
  x$alleles1 = round(x$sample1*x$freq1,0)#rbinom(1,size = x$sample1,prob = x$freq1)
  x$alleles2 = round(x$sample2*x$freq2,0)#rbinom(1,size = x$sample2,prob = x$freq2)
  return(x)})->minor

```

Now we'll set up the input file.
```{r,eval=F}
#setup_file<-file("./WFABC/4_generations.txt")
sink("./WFABC/4_generations.txt")
cat(paste0(nrow(minor)," ",2,"\n"))
cat("1,5\n")
for(i in 1:nrow(minor)){
  cat(paste(minor$sample1[i],minor$sample2[i],"\n",sep=","))
  cat(paste(minor$alleles1[i],minor$alleles2[i],"\n",sep=","))
}
sink()
```


Time to run the first command and estimate N_e

```{bash,eval=T}
cd /Users/jt/Documents/Analysis/HIVE/results/WFABC
../../scripts/WFABC_v1.1/binaries/Mac/wfabc_1 ./4_generations.txt
../../scripts/WFABC_v1.1/binaries/Mac/wfabc_2 -min_s -0.5 -max_s 0.5 -ploidy 1  4_generations.txt
```


# N_e posterior estimate

```{r}
post_N=read.table("./WFABC/4_generations_Ne_bootstrap.txt") 
plot(density(post_N[,1]),lwd=2,main="Ne Posterior",xlab="Ne") 
write_to_summary("ABC Ne:",mean(post_N$V1))
print(mean(post_N$V1))
```

```{r}
post_s=read.table("./WFABC/4_generations_posterior_s.txt")

minor$mean_s = rowMeans(post_s)
require(boa)
post_density.95<-apply(post_s,1,boa.hpd,1-0.95) 

minor<-cbind(minor,t(post_density.95))
#names(minor)[28]<-"Lower_Bound"
#names(minor)[29]<-"Upper_Bound"

minor <- rename(minor,Lower_Bound="Lower Bound",Upper_Bound = "Upper Bound")
minor %>% plyr::adply(1,function(x){
  x$selection = !(0>x$Lower_Bound & 0<x$Upper_Bound)
  return(x)}) -> minor

```


```{r}
post_s$mut_id<-1:nrow(post_s)

value_cols<-names(post_s)[grepl(pattern = "V\\d+",names(post_s),perl=T)]

post_s %>% gather(key = mut_id,value = s,V1:V1000) ->post_s.long

post_s.long<-post_s.long[,c(1,3)]

minor$mut_id<-1:nrow(minor)




post_s.long<-left_join(post_s.long,select(minor,mutation,mut_id,mean_s,donor_class,ENROLLID))

post_s.long<-post_s.long[order(post_s.long$mean_s,decreasing = T),]
post_s.long$y<-factor(post_s.long$mutation,levels =unique(post_s.long$mutation) )


post_s.long<- post_s.long %>%group_by(mut_id) %>%
  filter(s>minor$Lower_Bound[match(mut_id,minor$mut_id)], 
         s<minor$Upper_Bound[match(mut_id,minor$mut_id)])
      
  
  
write_to_summary("iSNV in samples exaclty 1 day apart:",length(unique(post_s.long$mut_id)))

joy_plot<-ggplot(post_s.long, aes(x=s, y=y, group=mut_id, height=..density..,fill=donor_class)) +
     geom_density_ridges(scale=4,rel_min_height = 0.04) +
     theme_joy()+ ylab("")+
    scale_fill_manual(labels  =c( "Nonsynonymous","Synonymous"),
                    name="",values=cbPalette[c(1,4)])+
    theme(axis.text.y = element_blank(),legend.position = "none")+
  geom_vline(xintercept = 0,linetype=2)
joy_plot
save_plot("./Figures/Figure2E.pdf", joy_plot,
          base_aspect_ratio = 1.3)


embed_fonts("./Figures/Figure2E.pdf")

write.csv(select(post_s.long,selection.coef = s,mutation,class=donor_class,ENROLLID),"./Figures/data/Figure2E.csv")
```



```{r,eval=F}
iqr_min <-function(x) quantile(x,probs = 0.25)
iqr_max <-function(x) quantile(x,probs = 0.75)
s_dotplot<-ggplot(minor,aes(y=mean_s,x=donor_class,fill=donor_class))+
  geom_dotplot(stackdir = "center",binaxis = 'y',binwidth = 0.02,dotsize = 1,
               position=position_dodge(width = 1)) +
  stat_summary(fun.y = "median",fun.ymin =  "iqr_min",fun.ymax = "iqr_max",
               geom = "crossbar",
               position = position_dodge(width = 1,preserve = 'single'),
               aes(color = donor_class,fill=NA))+
  scale_fill_manual(labels  =c( "Nonsynonymous","Synonymous"),
                    name="",values=cbPalette[c(1,4)])+
  scale_color_manual(labels  ="",name="",values=cbPalette[c(1,4)])+
  theme(legend.position = 'none')+xlab("") + ylab("Mean s")

minor<-minor[order(-minor$Lower_Bound),]
minor$y = 1:nrow(minor)
s_segment<-ggplot(minor,aes(x=Lower_Bound,xend = Upper_Bound,y = y, yend=y))+
  geom_segment(aes(color=donor_class),lineend = "butt")+
  scale_color_manual(labels  ="",name="",values=cbPalette[c(1,4)])+
  xlab("s")+
  theme(legend.position = 'none',
        axis.ticks.y =element_blank(),
        axis.line.y=element_blank())+ylab("")+scale_y_continuous(breaks = c())+
  geom_vline(xintercept = 0,color='red',linetype=2)+
  geom_point(aes(x=Lower_Bound,y=y,color=donor_class),shape=108,size=2)+
  geom_point(aes(x=Upper_Bound,y=y,color=donor_class),shape=108,size=2)+
  geom_point(aes(x=mean_s,y=y,color=donor_class))

s_dotplot
s_segment

save_plot("./Figures/Figure2E1.pdf", s_dotplot,
          base_aspect_ratio = 1.3)
save_plot("./Figures/Figure2E2.pdf", s_segment,
          base_aspect_ratio = 1.3)
```

```{r,eval=F}
minor$chr<-factor(minor$chr,levels = rev(c("PB2","PB1","PA","HA","NP","NR","M","NS"))) # Set the segments as factors with PB2 on top
chrs<-read.csv("../data/reference/segs.csv",stringsAsFactors = T) # get the start and stop of each OR for each segment (2014-2015 used as reference)

chrs$chr<-factor(chrs$chr,levels=levels(minor$chr)) # set factors on the is meta data

genome_loc.p<- ggplot(minor,aes(x=pos,y=chr)) +
  geom_point(aes(color=donor_class),shape=108,size=5) +
  geom_segment(data=chrs,aes(x = start, y = chr, xend = stop,yend = chr)) +
  ylab("")+ xlab("") + 
  theme(axis.ticks =element_blank(),
        axis.line.x = element_blank(),
        axis.line.y=element_blank())+
  scale_x_continuous(breaks=c())+
  scale_color_manual(name="",values=cbPalette[c(1,4)])+
  theme(legend.position = "none") + 
  geom_point(data = subset(minor,selection==T), aes(x=pos,y=as.numeric(chr)+0.3,shape=as.factor(ENROLLID )))

genome_loc.p


save_plot("./Figures/Figure2F.pdf", genome_loc.p,
          base_aspect_ratio = 1.3)
```


```{r}
subset(minor,selection==T)->selected

qual %>% filter(freq.var<0.5) ->qual_min
selected %>% rowwise() %>% 
  mutate(OR = qual_min$OR[match(SPECID1_location,qual_min$SPECID_location)],
         Ref_AA = qual_min$Ref_AA[match(SPECID1_location,qual_min$SPECID_location)],
         AA_pos = qual_min$AA_pos[match(SPECID1_location,qual_min$SPECID_location)],
         Var_AA = qual_min$Var_AA[match(SPECID1_location,qual_min$SPECID_location)]) ->selected

selected<-selected[order(selected$mean_s),]

kable(subset(selected,select=c(ENROLLID,mutation,donor_class,mean_s,OR,Ref_AA,AA_pos,Var_AA)))

write_to_summary("Nonneutral SPECID-iSNV-class:",paste(selected$mutation,collapse = ", "))


```
